# Generated by Django 3.2 on 2021-04-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
